OnlinTicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlinTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }



    }
}

OnlinTicariOtomasyon/Controllers/CariPanelController.cs
using OnlinTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace OnlinTicariOtomasyon.Controllers
{
    public class CariPanelController : Controller
    {
        // GET: CariPanel
        Context c = new Context();
        [Authorize]

        public ActionResult Index()
        {
            var mail = (string)Session["CariMail"];
            var degerler = c.mesajlars.Where(x => x.Alıcı == mail).ToList();
            ViewBag.m = mail;
            var mailid = c.Carilers.Where(x => x.CariMail == mail).Select(y => y.Cariid).FirstOrDefault();
            ViewBag.mid = mailid;
            var toplamsatis = c.SatisHarakets.Where(x => x.Cariid == mailid).Count();
            ViewBag.toplamsatis = toplamsatis;
            var toplamtuar = c.SatisHarakets.Where(x => x.Cariid == mailid).Sum(y => y.ToplamTutar);
            ViewBag.toplamtutar = toplamtuar;
            var toplamurunsayisi = c.SatisHarakets.Where(x => x.Cariid == mailid).Sum(y => y.Adet);
            ViewBag.toplamurunsayisi = toplamurunsayisi;
            var adsoyad = c.Carilers.Where(x => x.CariMail == mail).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.adsoyad = adsoyad;
            return View(degerler); 
        }

        public ActionResult Siparislerim()
        {
            var mail = (string)Session["CariMail"];
            var id = c.Carilers.Where(x => x.CariMail == mail.ToString()).Select(y => y.Cariid).FirstOrDefault();
            var degerler = c.SatisHarakets.Where(x => x.Cariid == id).ToList();
            return View(degerler);
        }

        public ActionResult GelenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var mesajlar = c.mesajlars.Where(x=>x.Alıcı==mail).OrderByDescending(x=>x.MesajID).ToList();
            var gelensayisi = c.mesajlars.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.mesajlars.Count(x => x.Göndetici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(mesajlar);
        }

        public ActionResult GidenMesajlar()
        {
            var mail = (string)Session["CariMail"];
            var mesajlar = c.mesajlars.Where(x => x.Göndetici == mail).OrderByDescending(x => x.MesajID).ToList();
            var gelensayisi = c.mesajlars.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.mesajlars.Count(x => x.Göndetici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(mesajlar);
        }

        public ActionResult MesajDetay(int id)
        {
            var degerler = c.mesajlars.Where(x => x.MesajID == id).ToList();
            var mail = (string)Session["CariMail"];
            var gelensayisi = c.mesajlars.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.mesajlars.Count(x => x.Göndetici == mail).ToString();
            ViewBag.d2 = gidensayisi;
            return View(degerler);
        }


        [HttpGet]
        public ActionResult YeniMesaj()
        {
            var mail = (string)Session["CariMail"];
            var gelensayisi = c.mesajlars.Count(x => x.Alıcı == mail).ToString();
            ViewBag.d1 = gelensayisi;
            var gidensayisi = c.mesajlars.Count(x => x.Göndetici == mail).ToString();
            ViewBag.d2 = gidensayisi;

            return View();
        }

        [HttpPost]
        public ActionResult YeniMesaj(mesajlar m)
        {
            var mail = (string)Session["CariMail"];
            m.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            m.Göndetici = mail;
            c.mesajlars.Add(m);
            c.SaveChanges();
            return View();
        }

        public ActionResult KargoTakip(string p)
        {
            var k = from x in c.KargoDetays select x;
           
            k = k.Where(y => y.TakipKodu.Contains(p));
           
            return View(k.ToList());
        }

        public ActionResult CariKargoTakip(string id)
        {
            var degerler = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();

            return View(degerler);
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }

        public PartialViewResult Partial1()
        {
            var mail = (string)Session["CariMail"];
            var id = c.Carilers.Where(x => x.CariMail == mail).Select(y => y.Cariid).FirstOrDefault();
            var caribul = c.Carilers.Find(id);
            return PartialView("Partial1", caribul);//KategoriGetir sayfasına döndür, kategori değişkenimle beraber yap
         
        }

        public PartialViewResult Partial2()
        {
            var veriler = c.mesajlars.Where(x => x.Göndetici == "admin").ToList();
            return PartialView(veriler);
        }

        public ActionResult CariBilgiGuncelle(Cariler cr)
        {
            var cari = c.Carilers.Find(cr.Cariid);
            cari.CariAd = cr.CariAd;// sağ taraftaki onun yeni değeri
            cari.CariSoyad = cr.CariSoyad;// sağ taraftaki onun yeni değeri
            cari.CariSifre = cr.CariSifre;// sağ taraftaki onun yeni değeri
            c.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

OnlinTicariOtomasyon/Views/CariPanel/CariKargoTakip.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<KargoTakip>

@{

    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>


    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Aciklama</td>
            <td>@x.TarihZaman</td>

        </tr>
    }
</table>

OnlinTicariOtomasyon/Views/CariPanel/Index.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<mesajlar>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}



<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | User Profile</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body class="hold-transition sidebar-mini">

    <div class="wrapper">

        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Content Wrapper. Contains page content -->
        <!-- Content Header (Page header) -->

        <section class="content-header">

            <div class="container-fluid">

                <div class="row mb-2">

                    <div class="col-sm-6">

                        <h1>Profilim</h1>

                    </div>



                </div>

            </div><!-- /.container-fluid -->

        </section>

        <!-- Main content -->

        <section class="content">

            <div class="container-fluid">

                <div class="row">

                    <div class="col-md-3">

                        <!-- Profile Image -->

                        <div class="card card-primary card-outline">

                            <div class="card-body box-profile">

                                <div class="text-center">

                                    <img class="profile-user-img img-fluid img-circle"
                                         src="~/AdminLTE-3.0.4/dist/img/avatar.png"
                                         alt="User profile picture">

                                </div>

                                
                                    <h3 class="profile-username text-center">@ViewBag.adsoyad</h3>

                                    <p class="text-muted text-center">@ViewBag.m</p>
                               

                                <ul class="list-group list-group-unbordered mb-3">

                                    <li class="list-group-item">

                                        <b>Toplam Satış:</b> <a class="float-right">@ViewBag.toplamsatis</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Tutar:</b> <a class="float-right">@ViewBag.toplamtutar ₺</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Ürün Sayısı:</b> <a class="float-right">@ViewBag.toplamurunsayisi</a>

                                    </li>

                                </ul>

                                <a href="/CariPanel/KargoTakip/" class="btn btn-primary btn-block"><b>Kargo Takip</b></a>

                            </div>

                            <!-- /.card-body -->

                        </div>

                        <!-- /.card -->
                        <!-- About Me Box -->

                        <div class="card card-primary">

                            <div class="card-header">

                                <h3 class="card-title">About Me</h3>

                            </div>

                            <!-- /.card-header -->
                            
                                <div class="card-body">

                                    <strong><i class="fas fa-book mr-1"></i> Meslek</strong>

                                    <p class="text-muted">

                                        Yazılım Mühendisi 

                                    </p>

                                    <hr>

                                    <strong><i class="fas fa-map-marker-alt mr-1"></i> Şehir</strong>

                                    <p class="text-muted">Ankara</p>

                                    <hr>

                                    <strong><i class="fas fa-pencil-alt mr-1"></i> Telefon</strong>

                                    <p class="text-muted">

                                    <p class="text-muted">(532) 123-4567</p>

                                    </p>

                                    <hr>

                                    <strong><i class="far fa-file-alt mr-1"></i> Duyurular</strong>

                                    <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>

                                </div>
                            
                            <!-- /.card-body -->

                        </div>

                        <!-- /.card -->

                    </div>

                    <!-- /.col -->

                    <div class="col-md-9">

                        <div class="card">

                            <div class="card-header p-2">

                                <ul class="nav nav-pills">

                                    <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Mesajlar</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Zaman Serisi</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ayarlar</a></li>

                                </ul>

                            </div><!-- /.card-header -->

                            <div class="card-body">

                                <div class="tab-content">

                                    <div class="active tab-pane" id="activity">

                                        <!-- Post -->
                                        @foreach(var x in Model) {
                                        <div class="post">

                                            <div class="user-block">

                                                <img class="img-circle img-bordered-sm" src="~/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="user image">

                                                <span class="username">

                                                    <a href="#">@x.Göndetici</a>

                                                    <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>

                                                </span>

                                                <span class="description">@x.Konu @x.Tarih.ToShortDateString()</span>

                                            </div>

                                            <!-- /.user-block -->

                                            <p>

                                               @x.icerik

                                            </p>

                                        </div>
                                        }
                                    </div>

                                    <!-- /.tab-pane -->

                                    <div class="tab-pane" id="timeline">

                                        <!-- The timeline -->

                                        @Html.Action("Partial2", "CariPanel");

                                    </div>

                                    <!-- /.tab-pane -->

                                    <div class="tab-pane" id="settings">

                                          @Html.Action("Partial1", "CariPanel");

                                    </div>

                                    <!-- /.tab-pane -->

                                </div>

                                <!-- /.tab-content -->

                            </div><!-- /.card-body -->

                        </div>

                        <!-- /.nav-tabs-custom -->

                    </div>

                    <!-- /.col -->

                </div>

                <!-- /.row -->

            </div><!-- /.container-fluid -->

        </section>

        <!-- /.content -->

    </div>

    <!-- /.content-wrapper -->

    <footer class="main-footer">

        <div class="float-right d-none d-sm-block">

            <b>Version</b> 3.0.4

        </div>

        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights

        reserved.

    </footer>

    <!-- Control Sidebar -->

    <aside class="control-sidebar control-sidebar-dark">

        <!-- Control sidebar content goes here -->

    </aside>

    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

OnlinTicariOtomasyon/Views/CariPanel/KargoTakip.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<KargoDetay>

@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<br />
@using (Html.BeginForm("KargoTakip", "CariPanel", FormMethod.Get))
{

    <p>
        Kargo Takip Numarası: @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </p>

}


<table class="table table-bordered" style="margin-top:20px;">
    <tr>

        <th>Personel</th>
        <th>Alıcı</th>
        <th>Takip Kodu</th>
        <th>Tarih </th>
        <th>Detaylar</th>

    </tr>
    @foreach (var k in Model)
    {

        <tr>
            <td>
                @k.Personel
            </td>
            <td>
                @k.Alici
            </td>
            <td>
                @k.TakipKodu
            </td>
            <td>
                @k.Tarih
            </td>
            <td><a href="/CariPanel/KargoTakip/@k.TakipKodu" class="btn btn-danger">Detaylar</a></td>
        </tr>
    }
</table>

OnlinTicariOtomasyon/Views/CariPanel/MesajDetay.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<mesajlar>
@{

    ViewBag.Title = "MesajDetay";

    Layout = "~/Views/Shared/_CariLayout.cshtml";

}



<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>AdminLTE 3 | Read Mail</title>

    <!-- Tell the browser to be responsive to screen width -->

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

    <!-- Ionicons -->

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->

    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">

    <!-- Google Font: Source Sans Pro -->

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>

<body>

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->

    <section class="content-header">

        <div class="container-fluid">

            <div class="row mb-2">

                <div class="col-sm-6">

                    <h1>Mesaj Detayları</h1>

                </div>

            </div>

        </div><!-- /.container-fluid -->

    </section>

    <!-- Main content -->

    <section class="content">

        <div class="container-fluid">

            <div class="row">

                <div class="col-md-3">

                    <a href="compose.html" class="btn btn-primary btn-block mb-3">Yeni Mesaj Oluştur</a>

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Klasörler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item active">

                                    <a href="/CariPanel/GelenMesajlar/" class="nav-link">

                                        <i class="fas fa-inbox"></i> Gelen Kutusu

                                        <span class="badge bg-primary float-right">@ViewBag.d1</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="/CariPanel/GidenMesajlar/" class="nav-link">

                                        <i class="far fa-envelope"></i> Gönderdiğim Mesajlar
                                        <span class="badge bg-danger float-right">@ViewBag.d2</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-file-alt"></i> Taslaklar
                                        <span class="badge bg-fuchsia float-right">0</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="fas fa-filter"></i> Gereksizler

                                        <span class="badge bg-warning float-right">7</span>

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                                        <span class="badge bg-gradient-cyan float-right">1</span>

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                    <div class="card">

                        <div class="card-header">

                            <h3 class="card-title">Filtreler</h3>

                            <div class="card-tools">

                                <button type="button" class="btn btn-tool" data-card-widget="collapse">

                                    <i class="fas fa-minus"></i>

                                </button>

                            </div>

                        </div>

                        <div class="card-body p-0">

                            <ul class="nav nav-pills flex-column">

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-danger"></i>

                                        Önemliler

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-warning"></i> Promosyonlar

                                    </a>

                                </li>

                                <li class="nav-item">

                                    <a href="#" class="nav-link">

                                        <i class="far fa-circle text-primary"></i>

                                        Sosyal Medya Mesajları

                                    </a>

                                </li>

                            </ul>

                        </div>

                        <!-- /.card-body -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->

                @foreach(var x in Model) {

                <div class="col-md-9">

                    <div class="card card-primary card-outline">

                        <div class="card-header">

                            <h3 class="card-title">Mesajı Oku</h3>

                            <div class="card-tools">

                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>

                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>

                            </div>

                        </div>

                        <!-- /.card-header -->

                        <div class="card-body p-0">

                            <div class="mailbox-read-info">

                                <h5>Konu: @x.Konu</h5>

                                <h6>

                                    Gönderen: @x.Göndetici

                                    <span class="mailbox-read-time float-right">@x.Tarih</span>

                                </h6>

                            </div>

                            <!-- /.mailbox-read-info -->

                            <div class="mailbox-controls with-border text-center">

                                <div class="btn-group">

                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Sil">

                                        <i class="far fa-trash-alt"></i>

                                    </button>

                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Yanıtla">

                                        <i class="fas fa-reply"></i>

                                    </button>

                                    <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Mesaj İlet">

                                        <i class="fas fa-share"></i>

                                    </button>

                                </div>

                                <!-- /.btn-group -->

                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">

                                    <i class="fas fa-print"></i>

                                </button>

                            </div>

                            <!-- /.mailbox-controls -->

                            <div class="mailbox-read-message">

                                <p>Merhaba</p>

                                <p>

                                    @x.icerik


                                </p>





                            </div>

                            <!-- /.mailbox-read-message -->

                        </div>

                        <!-- /.card-body -->
                        <!-- /.card-footer -->

                        <div class="card-footer">

                            <div class="float-right">

                                <button type="button" class="btn btn-default"><i class="fas fa-reply"></i> Yanıtla</button>

                                <button type="button" class="btn btn-default"><i class="fas fa-share"></i> Mesaj İlet</button>

                            </div>

                            <button type="button" class="btn btn-default"><i class="far fa-trash-alt"></i> Sil</button>

                            <button type="button" class="btn btn-default"><i class="fas fa-print"></i> Yazdır</button>

                        </div>

                        <!-- /.card-footer -->

                    </div>

                    <!-- /.card -->

                </div>

                <!-- /.col -->
                }
            </div>

            <!-- /.row -->

        </div>

    </section>

    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->

    <script src="`~AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->

    <script src="~AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- AdminLTE App -->

    <script src="~AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>

    <!-- AdminLTE for demo purposes -->

    <script src="~AdminLTE-3.0.4/dist/js/demo.js"></script>

</body>

</html>

OnlinTicariOtomasyon/Views/CariPanel/Partial1.cshtml
@model OnlinTicariOtomasyon.Models.Siniflar.Cariler


@using (Html.BeginForm("CariBilgiGuncelle", "CariPanel",FormMethod.Post))
{



<form class="form-horizontal">
    @*<div class="form-group row">

        <label for="inputName" class="col-sm-2 col-form-label">Id</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.Cariid, new { @class = "form-control" })

        </div>

    </div>*@

    @Html.HiddenFor(x=>x.Cariid)

    <div class="form-group row">

        <label for="inputName" class="col-sm-2 col-form-label">Ad</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputEmail" class="col-sm-2 col-form-label">Soyadı</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputName2" class="col-sm-2 col-form-label">Mail Adresi</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputExperience" class="col-sm-2 col-form-label">Şehir</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <label for="inputSkills" class="col-sm-2 col-form-label">Şifre</label>

        <div class="col-sm-10">

            @Html.TextBoxFor(x => x.CariSifre, new { @class = "form-control" })

        </div>

    </div>

    <div class="form-group row">

        <div class="offset-sm-2 col-sm-10">

            <div class="checkbox">

                <label>

                    <input type="checkbox"> Bilgileri okudum <a href="#">Şifre değiştirme şartlarını kabul ediyorum</a>

                </label>

            </div>

        </div>

    </div>

    <div class="form-group row">

        <div class="offset-sm-2 col-sm-10">

            <button type="submit" class="btn btn-danger">Güncelle</button>

        </div>

    </div>

</form>
}

OnlinTicariOtomasyon/Views/CariPanel/Partial2.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<mesajlar>
@foreach(var x in Model) {
<div class="timeline timeline-inverse">

    <!-- timeline time label -->

    <div class="time-label">

        <span class="bg-warning">

            @x.Tarih.ToShortDateString()

        </span>

    </div>

    <!-- /.timeline-label -->
    <!-- timeline item -->

    <div>

        <i class="fas fa-envelope bg-primary"></i>

        <div class="timeline-item">


            <h3 class="timeline-header"><a href="#">@x.Konu</a></h3>

            <div class="timeline-body">


                @x.icerik


            </div>



        </div>

    </div>

  
</div>
}

OnlinTicariOtomasyon/Views/CariPanel/Siparislerim.cshtml
@using OnlinTicariOtomasyon.Models.Siniflar
@model List<SatisHaraket>

@{
    ViewBag.Title = "Siparislerim";
    Layout = "~/Views/Shared/_CariLayout.cshtml";
}

<br />
<h2>Sipariş Geçmişim</h2>
<br />

<table class=" table table-bordered ">
    <tr>
        <th>Ürün adı</th>
        <th>Fiyat</th>
        <th>Tarih</th>
    </tr>
    @foreach(var x in Model) {
    <tr>

        <td>@x.Urun.UrunAd</td>
        <td>@x.Fiyat</td>
        <td>@Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")</td>
    </tr>
    }
</table>